asr/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from users import views as user_views
from student import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('student.urls')),
    path('register/',user_views.register,name='register'),
    path('profile/',user_views.profile, name='profile'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('ajax/load-profile',views.load_profile,name='ajax_load_profile')
]

student/urls.py
from django.urls import path
from . import views
from .views import (
AddStudent,
ShowList,
ShowJob,
AddJob,
AddMarriage,
ShowMarriageList
)
app_name = 'student'

urlpatterns = [
    path('',views.home, name='home'),
    path('add/',AddStudent.as_view(), name='add'),
    path('view/',ShowList.as_view(), name='table'),
    path('add-job/',AddJob.as_view(), name='add-job'),
    path('view-job/',ShowJob.as_view(), name='view-job'),
    path('add-marriage',AddMarriage.as_view(), name='add-marriage'),
    path('view-marriage',ShowMarriageList.as_view(), name='view-marriage')
]

student/models.py
from django.db import models
from datetime import date
from django.contrib.auth.models import User
import datetime
from django.urls import reverse
# Create your models here.
class Student(models.Model):
    GENDER =(
        ('M','Male'),
        ('F','Female'),
    )
    EDUCATION = (
        ('10','10th Pass'),
        ('12','12th Pass'),
        ('D','Diploma'),
    )
    #stid = models.IntegerField(primary_key=True)
    name = models.CharField(max_length=30)
    age = models.IntegerField()
    sex = models.CharField(max_length=1,default=('F'),choices=GENDER)
    date_of_admission = models.DateField(default=date.today())
    date_of_leaving = models.DateField(null=True,blank=True)
    education = models.CharField(max_length=30,choices=EDUCATION)
    height = models.IntegerField(help_text='Please enter height in cms')
    def __str__(self):
         return self.name
    def get_absolute_url(self):
        return reverse('student:table')

class Marriage(models.Model):
    MARITAL =(
        ('M','Married'),
        ('UM','Unmarried'),
    )
    student = models.OneToOneField(Student,on_delete=models.CASCADE)
    ailments = models.CharField(blank=True,max_length=100)
    job = models.CharField(max_length=20,blank=True)
    preferences = models.TextField(default=' ')
    status =  models.CharField(max_length=30,choices=MARITAL)
    
    def get_absolute_url(self):
        return reverse('student:view-marriage')

class Job(models.Model):
    student = models.OneToOneField(Student,on_delete=models.CASCADE)
    preferred_location = models.TextField(default=' ')
    date_of_joining = models.DateField(default=date(1000, 1, 1))
    #qualification
    future_preferences = models.TextField()
    job_timings = models.TextField()
    def get_absolute_url(self):
        return reverse('student:view-job')

users/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default='default.jpg', upload_to='profile_pics')

    def __str__(self):
        return f'{self.user.username} Profile'

# Create your models here.

student/forms.py
from django import forms
from .models import Student,Job,Marriage

class StudentForm(forms.ModelForm):
    class Meta:
        model= Student
        fields=('name','age','sex','date_of_admission','date_of_leaving','education', 'height')

class JobForm(forms.ModelForm):
    class Meta:
        model= Job
        fields=('student','preferred_location','date_of_joining','future_preferences','job_timings')
class MarriageForm(forms.ModelForm):
    class Meta:
        model= Marriage
        fields=('student','job','ailments','preferences', 'status')

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password']

student/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from django.views.generic import (
    CreateView,
    ListView
)
from .models import Student,Job,Marriage
from .forms import StudentForm,JobForm,MarriageForm
from django.urls import reverse_lazy
# Create your views here.
def home(request):
    return render(request = request,template_name="student/dashboard.html")

def load_profile(reqeust):
    return render(request = request,template_name="student/profile_dropdown.html")

class ShowList(ListView):
    model = Student
    template_name = 'student/table.html'
    context_object_name = 'students'
    ordering = ['-date_of_admission']

class AddStudent(CreateView):
    model = Student
    form_class = StudentForm
    success_url = reverse_lazy('student:table')

class AddJob(CreateView):
    model = Job
    form_class = JobForm
    success_url = reverse_lazy('student:view-job')

class ShowJob(ListView):
    model = Job
    template_name = 'student/view-job.html'
    context_object_name = 'jobs'
class AddMarriage(CreateView):
    model = Marriage
    form_class = MarriageForm
    success_url = reverse_lazy('student:view-marriage')

class ShowMarriageList(ListView):
    model = Marriage
    template_name = 'student/view-marriage.html'
    context_object_name = 'marriages'

users/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .forms import UserRegisterForm
# Create your views here.
def register(request):
    if request.method == 'POST':
         form = UserRegisterForm(request.POST)
         if form.is_valid():
             form.save()
             username = form.cleaned_data.get('username')
             messages.success(request,f'Your account has been created! You are now able to log in !')
             return redirect('users:login')
    else:
        form = UserRegisterForm()
    return render(request, 'users/register.html', {'form': form})

@login_required

def profile(request):
    return render(request, 'users/profile.html')

student/templates/student/dashboard.html
<!--
=========================================================
* Material Dashboard Dark Edition - v2.1.0
=========================================================

* Product Page: https://www.creative-tim.com/product/material-dashboard-dark
* Copyright 2019 ASRA (http://www.creative-tim.com)

* Coded by www.creative-tim.com

=========================================================

* The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
-->
{% extends "student/base.html" %}
{% load static %}
{% block content %}

            <div class="col-xl-12 col-lg-12">
              <div class="card card-chart">
              <div class="card-header card-header-primary">
                <h4 class="card-title">Welcome Admin !!</h4>
                <p class="card-category"> Rajvendra Puran Bal Niketan, Patiala,Punjab</p>
              </div>
            </div>
            </div>
            <div class="col-xl-4 col-lg-12">
              <div class="card card-chart">
                <div class="card-header card-header-success">
                  <div class="ct-chart" id="dailySalesChart"></div>
                </div>
                <div class="card-body">
                  <h4 class="card-title">Resident Data</h4>
                  <p class="card-category">
                    <span class="text-success"><i class="fa fa-long-arrow-up"></i> 15% </span> Increase in Residents</p>
                </div>
                <div class="card-footer">
                  <div class="stats">
                    <i class="material-icons">access_time</i> updated 4 minutes ago
                  </div>
                </div>
              </div>
            </div>
            <div class="col-xl-4 col-lg-12">
              <div class="card card-chart">
                <div class="card-header card-header-warning">
                  <div class="ct-chart" id="websiteViewsChart"></div>
                </div>
                <div class="card-body">
                  <h4 class="card-title">Orphanage Requirements</h4>
                  <p class="card-category">Donations from Public</p>
                </div>
                <div class="card-footer">
                  <div class="stats">
                    <i class="material-icons">access_time</i> Requirements sent 2 days ago
                  </div>
                </div>
              </div>
            </div>
            <div class="col-xl-4 col-lg-12">
              <div class="card card-chart">
                <div class="card-header card-header-danger">
                  <div class="ct-chart" id="completedTasksChart"></div>
                </div>
                <div class="card-body">
                  <h4 class="card-title">Rajvendra Puran Bal Niketan</h4>
                  <p class="card-category">Orphanage Staff</p>
                </div>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-xl-3 col-lg-6 col-md-6 col-sm-6">
              <div class="card card-stats">
                <div class="card-header card-header-warning card-header-icon">
                  <div class="card-icon">
                    <i class="material-icons">content_copy</i>
                  </div>
                  <p class="card-category">Used Space</p>
                  <h3 class="card-title">1/50
                    <small>GB</small>
                  </h3>
                </div>
                <div class="card-footer">
                  <div class="stats">
                    <i class="material-icons text-warning">warning</i>
                    <a href="#pablo" class="warning-link">Check the detailed distribution...</a>
                  </div>
                </div>
              </div>
            </div>
            <div class="col-xl-3 col-lg-6 col-md-6 col-sm-6">
              <div class="card card-stats">
                <div class="card-header card-header-success card-header-icon">
                  <div class="card-icon">
                    <i class="material-icons">store</i>
                  </div>
                  <p class="card-category">Revenue Generated</p>
                  <h3 class="card-title">Rs. 34,245</h3>
                </div>
                <div class="card-footer">
                  <div class="stats">
                    <i class="material-icons">date_range</i> Last 24 Hours
                  </div>
                </div>
              </div>
            </div>
            <div class="col-xl-3 col-lg-6 col-md-6 col-sm-6">
              <div class="card card-stats">
                <div class="card-header card-header-danger card-header-icon">
                  <div class="card-icon">
                    <i class="material-icons">info_outline</i>
                  </div>
                  <p class="card-category">Active staff members</p>
                  <h3 class="card-title">5</h3>
                </div>
                <div class="card-footer">
                  <div class="stats">
                    <i class="material-icons">local_offer</i> Tracked from Heroku
                  </div>
                </div>
              </div>
            </div>
            <div class="col-xl-3 col-lg-6 col-md-6 col-sm-6">
              <div class="card card-stats">
                <div class="card-header card-header-info card-header-icon">
                  <div class="card-icon">
                    <i class="material-icons">info_outline</i>
                  </div>
                  <p class="card-category">Website Hits</p>
                  <h3 class="card-title">+145</h3>
                </div>
                <div class="card-footer">
                  <div class="stats">
                    <i class="material-icons">update</i> Just Updated
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-lg-6 col-md-12">
              <div class="card">
              </div>
            </div>
            <div class="col-lg-6 col-md-12">
              <div class="card">
              </div>
            </div>

      {% endblock content %}

student/templates/student/job_form.html
<!--
=========================================================
* Material Dashboard Dark Edition - v2.1.0
=========================================================

* Product Page: https://www.creative-tim.com/product/material-dashboard-dark
* Copyright 2019 ASRA (http://www.creative-tim.com)

* Coded by www.creative-tim.com

=========================================================

* The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
-->
{% extends "student/base.html" %}
{% load static %}
{% load widget_tweaks %}
<!--{% load crispy_forms_tags %} -->

{% block content %}
            <div class="col-md-8">
              <div class="card">
                <div class="card-header card-header-primary">
                  <h4 class="card-title">Job Details</h4>
                  <p class="card-category">Fill in the details of the  job</p>
                </div>
                <div class="card-body">
                 
                  <form method="POST" id="JobForm">

                    {% csrf_token %}
                    <div class="row">
                      <div class="col-md-4">
                          <label class="bmd-label-floating">Resident</label>
                            {% render_field form.student class="form-control" %}
                        </div>
                      </div>

                        <div class="row">
                        <div class="col-md-6">
                          <label class="bmd-label-floating">Preffered Location</label>
                          {% render_field form.preferred_location class="form-control" %}
                        </div>
                      </div>

                    <div class="row">

                      <div class="col-md-4">
                          <label class="bmd-label-floating">Job Preference</label>
                        
                            {% render_field form.future_preferences class="form-control" %}
                        </div>
                      </div>

                    <div class="row">
                      <div class="col-md-8">
                          <label class="bmd-label-floating">Job Timings</label>
                       
                          {% render_field form.job_timings class="form-control" %}
                        </div>
                    </div>
                    <div class="row">
                      <div class="col-md-8">

                          <label class="bmd-label-floating">Date Of Joining</label>
                          
                          {% render_field form.date_of_joining class="form-control" %}
                        </div>

                    </div>
                   <!-- <div class="row">
                      <div class="col-md-5">
                        <div class="form-group">
                          <label class="bmd-label-floating">Country</label>
                          <input type="text" class="form-control">
                        </div>
                      </div>
                    </div>
                    <div class="row">
                      <div class="col-md-5">
                        <div class="form-group">
                          <label class="bmd-label-floating">Postal Code</label>
                          <input type="text" class="form-control">
                        </div>
                      </div>
                    </div>
                </div> -->

                    <button type="submit" id="submit_btn" class="btn btn-primary pull-right">Submit</button>
                    <div class="clearfix"></div>
                  </form>
                </div>

           <!--<div class="col-md-4">
              <div class="card card-profile">
                <div class="card-avatar">
                  <a href="#pablo">
                    <img class="img" src="../static/img/faces/marc.jpg" />
                  </a>
                </div>
                <div class="card-body">
                  <h6 class="card-category">CEO / Co-Founder</h6>
                  <h4 class="card-title">Alec Thompson</h4>
                  <p class="card-description">
                    Don't be scared of the truth because we need to restart the human foundation in truth And I love you like Kanye loves Kanye I love Rick Owens’ bed design but the back is...
                  </p>
                  <a href="#pablo" class="btn btn-primary btn-round">Follow</a>
                </div>
              </div>
            </div> -->
    {% endblock content %}

student/templates/student/profile_dropdown.html
<div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
    <option value="Edit Profile"><a class="dropdown-item" href="#"></a></option>
    <option value="Log Out"><a class="dropdown-item" href="{% url 'logout'}">Log Out</a></option>
  </div>

student/templates/student/student_list.html
<!--
=========================================================
* Material Dashboard Dark Edition - v2.1.0
=========================================================

* Product Page: https://www.creative-tim.com/product/material-dashboard-dark
* Copyright 2019 ASRA (http://www.creative-tim.com)

* Coded by www.creative-tim.com

=========================================================

* The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
-->
{% extends "student/base.html"%}
{% load static %}
{% block content %}

            <div class="col-md-12">
              <div class="card card-plain">
                <div class="card-header card-header-primary">
                  <h4 class="card-title ">Resident Details</h4>
                  <p class="card-category">General Info</p>
                </div>
                <div class="card-body">
                  <div class="table-responsive">
                    <table class="table table-hover">
                      <thead class=" text-primary">
                        <th>
                          ID
                        </th>
                        <th>
                          Name
                        </th>
                        <th>
                          Age
                        </th>
                        <th>
                          D.O.A.
                        </th>
                        <th>
                          D.O.L.
                        </th>
                        <th>
                          Gender
                        </th>
                      </thead>
                      <tbody>
                        <button class="btn btn-primary pull-center"><a href="{% url 'student:add-job' %}">Add Job</a></button>
                          <button class="btn btn-primary pull-center"><a href="{% url 'student:add-marriage' %}">Add Marital Status</a></button>
                        
                        {% for student in students %}
                        <tr>
                          <td>
                          {{ student.id }}
                          </td>
                          <td>
                            {{ student.name }}
                          </td>
                          <td>
                            {{ student.age }}
                          </td>
                          <td>
                            {{ student.date_of_admission }}
                          </td>
                          <td>
                            {{ student.date_of_leaving }}
                          </td>
                          <td>
                            {{ student.sex }}
                          </td>

                        {% endfor %}
                      </tbody>
                    </table>
                  </div>
                </div>
              </div>
            </div>
          <!--  <div class="col-md-12">
              <div class="card card-plain">
                <div class="card-header card-header-primary">
                  <h4 class="card-title mt-0"> Table on Plain Background</h4>
                  <p class="card-category"> Here is a subtitle for this table</p>
                </div>
                <div class="card-body">
                  <div class="table-responsive">
                    <table class="table table-hover">
                      <thead class="">
                        <th>
                          ID
                        </th>
                        <th>
                          Name
                        </th>
                        <th>
                          Country
                        </th>
                        <th>
                          City
                        </th>
                        <th>
                          Salary
                        </th>
                      </thead>
                      <tbody>
                        <tr>
                          <td>
                            1
                          </td>
                          <td>
                            Dakota Rice
                          </td>
                          <td>
                            Niger
                          </td>
                          <td>
                            Oud-Turnhout
                          </td>
                          <td>
                            $36,738
                          </td>
                        </tr>
                        <tr>
                          <td>
                            2
                          </td>
                          <td>
                            Minerva Hooper
                          </td>
                          <td>
                            Curaçao
                          </td>
                          <td>
                            Sinaai-Waas
                          </td>
                          <td>
                            $23,789
                          </td>
                        </tr>
                        <tr>
                          <td>
                            3
                          </td>
                          <td>
                            Sage Rodriguez
                          </td>
                          <td>
                            Netherlands
                          </td>
                          <td>
                            Baileux
                          </td>
                          <td>
                            $56,142
                          </td>
                        </tr>
                        <tr>
                          <td>
                            4
                          </td>
                          <td>
                            Philip Chaney
                          </td>
                          <td>
                            Korea, South
                          </td>
                          <td>
                            Overland Park
                          </td>
                          <td>
                            $38,735
                          </td>
                        </tr>
                        <tr>
                          <td>
                            5
                          </td>
                          <td>
                            Doris Greene
                          </td>
                          <td>
                            Malawi
                          </td>
                          <td>
                            Feldkirchen in Kärnten
                          </td>
                          <td>
                            $63,542
                          </td>
                        </tr>
                        <tr>
                          <td>
                            6
                          </td>
                          <td>
                            Mason Porter
                          </td>
                          <td>
                            Chile
                          </td>
                          <td>
                            Gloucester
                          </td>
                          <td>
                            $78,615
                          </td>
                        </tr>
                      </tbody>
                    </table>
                  </div>
                </div>
              </div>
            </div> -->

  {% endblock content %}

users/templates/users/login.html
{% extends "users/welcome.html" %}
{% load static %}
{% load widget_tweaks %}
{% block content %}


			<div class="wrap-login100">
				<form class="login100-form validate-form" method="POST">
					{% csrf_token %}
					<span class="login100-form-title p-b-34">
						Account Login
					</span>
					
					<div class="wrap-input100 wrap-input100 validate-input m-b-20" data-validate="Type user name">
						<input id="first-name" class="input100" type="text" name="username" placeholder="User name">
						<span class="focus-input100">{% render_field form.username class="focus-input100" %}</span>
					</div>
					<div class="wrap-input100 wrap-input100 validate-input m-b-20" data-validate="Type password">
						<input class="input100" type="password" name="pass" placeholder="Password">
						<span class="focus-input100">{% render_field form.password class="focus-input100" %}</span>
					</div>
					
					<div class="container-login100-form-btn">
						<button class="login100-form-btn">
							<a href="{% url 'student:home' %}">
							Sign in
							</a>
						</button>
					</div>

					 <!--<div class="w-full text-center p-t-27 p-b-239">
						<span class="txt1">
							Forgot
						</span>

						<a href="#" class="txt2">
							User name / password?
						</a>
					</div> -->

					<div class="w-full text-center">
						<span class="txt1">
							Need An Account?
						</span>
						<a href="{% url 'register' %}" class="txt3">
							Sign Up
						</a>
					</div>
				</form>

				<div class="login100-more" style="background-image: url('../static/img/bg-01.jpg');"></div>
			</div>
{% endblock content %}

users/templates/users/logout.html
{% extends "users/welcome.html" %}
{% load static %}
{% block content %}


			<div class="wrap-login100">
				<div >

				</div>
					<span class="login100-form-title p-b-20 p-t-100">
						You Have Logged Out Successfully !
					</span>
					
					<!--<div class="wrap-input100 rs1-wrap-input100 validate-input m-b-20" data-validate="Type user name">
						<input id="first-name" class="input100" type="text" name="username" placeholder="User name">
						<span class="focus-input100"></span>
					</div>
					<div class="wrap-input100 rs2-wrap-input100 validate-input m-b-20" data-validate="Type password">
						<input class="input100" type="password" name="pass" placeholder="Password">
						<span class="focus-input100"></span>
					</div>
					
					<div class="container-login100-form-btn">
						<button class="login100-form-btn">
							<a href='#'>
							Sign in
							</a>
						</button>
					</div> -->

					<div class="w-full text-center p-t-27 p-b-100">


						<a href="{% url 'login' %}" class="txt2">
							Click Here To Sign In Again
						</a>
					</div>

			</div>
{% endblock content %}

users/templates/users/register.html
{% extends "users/welcome.html" %}
{% load static %}
{% load widget_tweaks %}
{% block content %}


			<div class="wrap-login100">
				<form class="login100-form validate-form" method="POST">
					{% csrf_token %}
					<span class="login100-form-title p-b-34">
                        REGISTER
					</span>
					
					<div class="wrap-input100 validate-input m-b-20" data-validate="Type user name">
						<input id="username" class="input100" type="text" name="username" placeholder="User name">
						<span >{% render_field form.username class="focus-input100" %}</span>
                    </div>
					<div class="wrap-input100 validate-input m-b-20" data-validate="Type email">
						<input id="email" class="input100" type="text" name="email" placeholder="Email">
						<span>{% render_field form.email class="focus-input100" %}</span>
                    </div>
					<div class="wrap-input100 validate-input m-b-20" data-validate="Type password">
						<input class="input100" type="password" name="pass" placeholder="Password">
						<span class="focus-input100">{% render_field form.password class="focus-input100" %}</span>
					</div>

					<div class="container-login100-form-btn">
						<button class="login100-form-btn">
							<a href="{% url 'student:home' %}">
							Sign Up
							</a>
						</button>
					</div>

					<!-- <div class="w-full text-center p-t-27 p-b-239">
						<span class="txt1">
							Forgot
						</span>

						<a href="#" class="txt2">
							User name / password?
						</a>
					</div> -->

					<div class="w-full text-center">

						<span class="txt1">
							Already Have An Account?
						</span>
						<a href="{% url 'login' %}" class="txt3">
							Sign In
						</a>
					</div>
				</form>

				<div class="login100-more" style="background-image: url('../static/img/bg-01.jpg');"></div>
			</div>
{% endblock content %}